### PR TITLE
Changeivoicetype usecase done QA-66

### PR DESCRIPTION
**Pull request by Azarudeen1995**
Changeivoicetype usecase done QA-66

### CODE REVIEW

**Comment by karnanqa** [comment]
Small information for you @Azarudeen1995 
We have already all those codes for your ticket QA-66 excluded edit the invoice type field so you can reuse the code from POM

**Review by balasubramanyan — CHANGES_REQUESTED** [review]
Please use existing methods to create/invoice. 
Its in invoice.java page. please do  refer

**Comment by balasubramanyan** [comment]
> 
> 
> Small information for you @Azarudeen1995
> We have already all those codes for your ticket QA-66 excluded edit the invoice type field so you can reuse the code from POM

@karnanqa Do you have ticket with scenario ? please update if you have.
If not, please mention the page name and methods

**Comment by karnanqa** [comment]
> > Small information for you @Azarudeen1995
> > We have already all those codes for your ticket QA-66 excluded edit the invoice type field so you can reuse the code from POM
> 
> @karnanqa Do you have ticket with scenario ? please update if you have.
> If not, please mention the page name and methods

Sorry am not working on this cases and all,  but I just went through the scripts.

**Pull request merged**
