### PR TITLE
First commit by divya

### PR DESCRIPTION
**Pull request by Divya5976**
Added page model for contact screen
Added testcases in divya class

### CODE REVIEW

**Review by balasubramanyan — CHANGES_REQUESTED** [review]
in.InvoiceTab();
in.addinvoice();
c.Click_contacttab();
c.Add_contact();

i think need to change declaration name to full form to better understanding.
**in** to invoice or something mathing the usecase
**c** to contact

**Comment by Divya5976** [comment]
I will change and update.

**Comment by Divya5976** [comment]
I changed as per requirement kindly review.

**Review by balasubramanyan — APPROVED** [review]
Approved

**Review by balasubramanyan — CHANGES_REQUESTED** [review]
Add such exception if there is no records to display

public void Customer3_Assertion()
{
	try 
	{
		isdisplayed("//span[@data-row-index=\"0\" and @data-column=\"Customer.Account.Number\"]");//check the first row customer accoutn number present or not
	}
	catch (Exception e)
	{
		String a=gettext("(//div[@class=\"warning-message ng-binding\" and @ng-bind-html=\"message\" and contains(text(),'No records found')])[1]");
		String b="No records found";
		Assertion(b, a, "No records found - Assertion failed");
	}
}

**Review by balasubramanyan — CHANGES_REQUESTED** [review]
can you merge this work address test casse into the "Customer_Report.java" file itself
Commusoft-Stage2&Live/src/test/java/testcase/Customer_Report.java

**Review by balasubramanyan — APPROVED** [review]

**Pull request merged**
